before_install:
  - sudo add-apt-repository --yes ppa:hansjorg/rust
  - sudo add-apt-repository --yes ppa:cmrx64/cargo
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq rust-nightly cargo
  - sudo apt-get install -qq premake4
script:
  - cargo build
